# Generated by Django 5.2.8 on 2025-11-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to auto-generate.', max_length=10, unique=True)),
                ('target_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
